# src/comparison.py
import json
import os
from custom_vad import CustomVoiceActivityDetector

class DiarizationComparison:
    """
    Compare custom VAD with pyannote model
    """
    
    def __init__(self):
        self.custom_vad = CustomVoiceActivityDetector()
        self.comparison_results = {}
    
    def run_comparison(self, audio_path):
        """
        Run both models and compare results
        """
        print("\n" + "="*60)
        print("🔬 RUNNING MODEL COMPARISON")
        print("="*60)
        
        # 1. Run custom VAD
        print("\n📊 Running Custom VAD Model...")
        custom_segments, custom_stats = self.custom_vad.detect_speech(audio_path)
        print(f"   ✅ Custom VAD detected {len(custom_segments)} speech segments")
        
        # 2. Load pyannote segments (already generated by existing code)
        pyannote_path = 'outputs/pyannote_segments.json'
        if os.path.exists(pyannote_path):
            with open(pyannote_path, 'r', encoding='utf-8') as f:
                pyannote_segments = json.load(f)
            print(f"   ✅ Pyannote detected {len(pyannote_segments)} speech segments")
        else:
            # Fallback: read from speakers.json
            with open('outputs/speakers.json', 'r', encoding='utf-8') as f:
                pyannote_data = json.load(f)
            pyannote_segments = [{'start': seg['start'], 'end': seg['end']} 
                                 for seg in pyannote_data]
            print(f"   ✅ Pyannote detected {len(pyannote_segments)} speech segments")
        
        # 3. Calculate comparison metrics
        print("\n📈 Calculating Comparison Metrics...")
        metrics = self.custom_vad.calculate_metrics(custom_segments, pyannote_segments)
        
        # 4. Save custom results
        self._save_custom_results(custom_segments, custom_stats, audio_path)
        
        # 5. Prepare comparison report
        comparison_report = {
            'custom_model': {
                'name': 'Custom VAD (Energy + ZCR)',
                'segments': custom_segments,
                'stats': custom_stats,
                'segment_count': len(custom_segments)
            },
            'pyannote_model': {
                'name': 'Pyannote (State-of-the-art)',
                'segments': pyannote_segments,
                'segment_count': len(pyannote_segments)
            },
            'comparison_metrics': metrics,
            'recommendation': self._get_recommendation(metrics)
        }
        
        # Save comparison results
        with open('outputs/comparison_results.json', 'w', encoding='utf-8') as f:
            json.dump(comparison_report, f, indent=2, ensure_ascii=False)
        
        print("\n" + "="*60)
        print("📊 COMPARISON RESULTS")
        print("="*60)
        print(f"Custom VAD Segments: {len(custom_segments)}")
        print(f"Pyannote Segments: {len(pyannote_segments)}")
        print(f"Intersection over Union (IoU): {metrics['iou']*100:.1f}%")
        print(f"Agreement: {metrics['agreement_percentage']:.1f}%")
        print(f"F1 Score: {metrics['f1_score']:.3f}")
        print("="*60)
        
        return comparison_report
    
    def _save_custom_results(self, segments, stats, audio_path):
        """
        Save custom VAD results
        """
        output = {
            'audio_file': os.path.basename(audio_path),
            'segments': segments,
            'statistics': stats,
            'total_speech_time': sum(seg['duration'] for seg in segments),
            'num_segments': len(segments)
        }
        
        with open('outputs/custom_vad_results.json', 'w', encoding='utf-8') as f:
            json.dump(output, f, indent=2, ensure_ascii=False)
    
    def _get_recommendation(self, metrics):
        """
        Provide recommendation based on comparison
        """
        if metrics['f1_score'] > 0.8:
            return "Excellent! Custom VAD performs very close to pyannote."
        elif metrics['f1_score'] > 0.6:
            return "Good performance. Custom VAD shows promising results."
        elif metrics['f1_score'] > 0.4:
            return "Moderate performance. Could be improved with tuning."
        else:
            return "Custom VAD needs improvement. Consider adjusting thresholds."